/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ViewCancelledFlights extends javax.swing.JFrame {
    Connection con;
    String query;
    ResultSet rs, rss, rst1;
    Statement stmt, st;
    PreparedStatement ps, pst = null;
    
    /**
     * Creates new form ViewCancelledFlights
     */
    public ViewCancelledFlights() {
        initComponents();
    }
    
    public void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cancelFlight = new javax.swing.JButton();
        updateFlight = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Cancelled and Available Flights");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Cancelled Flights");

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight No", "Flight Name", "Source", "Destination", "Depart Time", "Arrival Time", "Flight Date", "Class", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight no", "Flight name", "Source", "Destination", "Depart Time", "Arrival Time", "Flight Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("Available Flights");

        cancelFlight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelFlight.setText("Cancel Flight");
        cancelFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFlightActionPerformed(evt);
            }
        });

        updateFlight.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateFlight.setText("Update Flight");
        updateFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateFlight)
                        .addGap(43, 43, 43)
                        .addComponent(cancelFlight)
                        .addGap(49, 49, 49)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        AdminRights ar = new AdminRights();
        ar.setVisible(true);
        close();
    }//GEN-LAST:event_backActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here: 
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightActionPerformed
        UpdateFlights uf = new UpdateFlights();
        if(jTable2.getSelectionModel().isSelectionEmpty())
        {
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
            int i=jTable1.getSelectedRow();
            String data = df.getValueAt(i, 0).toString();
            UpdateFlights.jTextField1.setText(df.getValueAt(i, 0).toString());
            UpdateFlights.jTextField2.setText(df.getValueAt(i, 1).toString());
            UpdateFlights.jTextField3.setText(df.getValueAt(i, 2).toString());
            UpdateFlights.jTextField4.setText(df.getValueAt(i, 3).toString());
            UpdateFlights.jTextField5.setText(df.getValueAt(i, 4).toString());
            UpdateFlights.jTextField6.setText(df.getValueAt(i, 5).toString());
            UpdateFlights.jTextField7.setText(df.getValueAt(i, 6).toString());
            try
            {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?allowMultiQueries=true", "root", "pinku");
                String sql = "select price from flights where flight_no= '" + data + "'";
                PreparedStatement pst = con.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while(rs.next())
                {
                    UpdateFlights.jTextField8.setText(rs.getString("price"));
                }
            }
            catch(ClassNotFoundException | SQLException | HeadlessException ex)
            {
                System.out.println(ex);
            }
        }
        else if(jTable1.getSelectionModel().isSelectionEmpty()){
            DefaultTableModel dtf=(DefaultTableModel)jTable2.getModel();
            int j=jTable2.getSelectedRow();
            UpdateFlights.jTextField1.setText(dtf.getValueAt(j, 0).toString());
            UpdateFlights.jTextField2.setText(dtf.getValueAt(j, 1).toString());
            UpdateFlights.jTextField3.setText(dtf.getValueAt(j, 2).toString());
            UpdateFlights.jTextField4.setText(dtf.getValueAt(j, 3).toString());
            UpdateFlights.jTextField5.setText(dtf.getValueAt(j, 4).toString());
            UpdateFlights.jTextField6.setText(dtf.getValueAt(j, 5).toString());
            UpdateFlights.jTextField7.setText(dtf.getValueAt(j, 6).toString());
            UpdateFlights.jTextField8.setText(dtf.getValueAt(j, 8).toString());
        }
        uf.setVisible(true);
        close();
    }//GEN-LAST:event_updateFlightActionPerformed

    private void cancelFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFlightActionPerformed
        DefaultTableModel df=(DefaultTableModel)jTable2.getModel();
                int i=jTable2.getSelectedRow();
                String data = df.getValueAt(i, 0).toString();
                int x=0;
                try
                {
                    Class.forName("com.mysql.cj.jdbc.Driver");  
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?allowMultiQueries=true", "root", "pinku");
                    PreparedStatement ps = con.prepareStatement("update flights set status = 'Cancelled' where flight_no = '" + data + "'");
                    ps.executeUpdate();
                    x++;
                    if(x > 0)
                    {
                        JOptionPane.showMessageDialog(null, "Flight Cancelled Successfully");
                    }
                    String sender = ""; //insert valid email id
                    String host = "smtp.gmail.com"; 
                    Properties properties = System.getProperties(); 
                    properties.put("mail.smtp.host", host);
                    properties.put("mail.smtp.port", "465");
                    properties.put("mail.smtp.ssl.enable", "true");
                    properties.put("mail.smtp.auth", "true");
                    Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("", ""); //insert sender email id and correspondinf correct password
                    }
                });
                   session.setDebug(true);
                   try
                   {
                       MimeMessage message = new MimeMessage(session);
                       message.setFrom(new InternetAddress(sender));
                       PreparedStatement pst = con.prepareStatement("select C_ID from pay where f_no='" + data + "'");
                       rs = pst.executeQuery();
                       while(rs.next())
                       {
                           PreparedStatement pss = con.prepareStatement("select email_id from reg where customer_id = '" + rs.getString("C_ID") + "'");
                           rss = pss.executeQuery();
                           while(rss.next())
                           {
                               message.addRecipients(Message.RecipientType.TO,InternetAddress.parse(rss.getString("email_id")));
                           }
                       }
                        message.setSubject("Flight Update Information");
                        message.setText("Your flight with number '" + data + "' has been cancelled due to technical issues. We are sorry for our inconvience. This is system generated mail, please don not reply to this mail. If you have any problem regarding this you can contact us +91-720128546");
                        Transport.send(message); 
                        JOptionPane.showMessageDialog(null, "Mail successfully sent");
                   }
                   catch(MessagingException ex)
                   {
                       System.out.println(ex.getMessage());
                   }
                   
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ViewCancelledFlights.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            ViewCancelledFlights vcf = new ViewCancelledFlights();
            vcf.setVisible(true);
                try{
                Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?allowMultiQueries=true", "root", "pinku");
                PreparedStatement pst = con.prepareStatement("select flight_no, flight_name, source, destination, depart_time, arr_time, flight_date from flights where status = 'Cancelled'");
                ResultSet rs = pst.executeQuery();
                DefaultTableModel model=(DefaultTableModel)vcf.jTable1.getModel();
                model.setRowCount(0);
                while(rs.next())
                {
                    Object[] row = {rs.getString("flight_no"), rs.getString("flight_name"), rs.getString("source"), rs.getString("destination"), rs.getString("depart_time"), rs.getString("arr_time"), rs.getString("flight_date")};
                    model.addRow(row);
                }
                PreparedStatement ps = con.prepareStatement("select * from flights where status = 'Available'");
                ResultSet rst = ps.executeQuery();
                DefaultTableModel model1=(DefaultTableModel)vcf.jTable2.getModel();
                model1.setRowCount(0);
                while(rst.next())
                {
                    Object[] row1 = {rst.getString("flight_no"), rst.getString("flight_name"), rst.getString("source"), rst.getString("destination"), rst.getString("depart_time"), rst.getString("arr_time"), rst.getString("flight_date"),rst.getString("class"), rst.getString("price")};
                    model1.addRow(row1);
                }
            }
            catch(ClassNotFoundException | SQLException | HeadlessException ex)
            {
                System.out.println(ex);  
            }
        
        close();
    }//GEN-LAST:event_cancelFlightActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCancelledFlights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewCancelledFlights().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cancelFlight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JButton updateFlight;
    // End of variables declaration//GEN-END:variables
}
